### ISSUE TITLE
[Feature Request] Reduce boot menu timeout on autoinstall 

### ISSUE THREAD

**Issue by toledo-labs** [dannf/ubuntu-server-netboot#26]
## Description
Reduce the timeout on the boot menu when AutoInstall is enabled. The boot menu option for 30 seconds is too long on AutoInstall.

## Possible Solution
Set the timeout from 30 seconds to 1-10 seconds

## Additional context
Coded solution should replace "timeout=30" in the grub file or use a regExpression to update the timeout variable

**Comment by dannf** [comment]
Fixed in 3fe1056f27a9fc91433951d4072501f6b447efe9
