### ISSUE TITLE
option --iso and --url should be mutually exclusive

### ISSUE THREAD

**Issue by tai271828** [dannf/ubuntu-server-netboot#3]
When providing a local copy of iso, `--url` is unnecessary.

The current behavior:
```
$ ./ubuntu-server-netboot.py  --iso ../ubuntu-20.04.1-live-server-arm64.iso
usage: ubuntu-server-netboot.py [-h] [-e EXTRA_ARGS] [--iso ISO] [-o OUT_DIR]
                                --url URL
ubuntu-server-netboot.py: error: the following arguments are required: --url
```

**Comment by dannf** [comment]
`--url` is actually still necessary because it is needs to be added to the bootloader configuration. (`subiquity` needs to download it at runtime). I tried to describe this in the `README.md` - but please feel free to clarify the wording in a PR

**Comment by tai271828** [comment]
I did not read `README.md` carefully enough. Thanks for pointing it out.
